# TCL File Generated by Component Editor 7.2 on:
# Wed Apr 08 17:48:57 EDT 2009
# DO NOT MODIFY

set_source_file "dm9000a.vhd"
set_module "dm9000a"
set_module_description ""
set_module_property "className" "dm9000a"
set_module_property "displayName" "DM9000a series ethernet"
set_module_property "group" "Ethernet"
set_module_property "libraries" [ list "ieee.std_logic_1164.all" "std.standard.all" ]
set_module_property "synthesisFiles" "dm9000a.vhd"
set_module_property "version" "7.2"

# Module parameters

# Interface clock
add_interface "clock" "clock" "sink" "asynchronous"
# Ports in interface clock
add_port_to_interface "clock" "iRST_N" "reset_n"

# Interface export_0
add_interface "export_0" "conduit" "start" "clock"
# Ports in interface export_0
add_port_to_interface "export_0" "ENET_DATA" "export"
add_port_to_interface "export_0" "ENET_CMD" "export"
add_port_to_interface "export_0" "ENET_RD_N" "export"
add_port_to_interface "export_0" "ENET_WR_N" "export"
add_port_to_interface "export_0" "ENET_CS_N" "export"
add_port_to_interface "export_0" "ENET_RST_N" "export"
add_port_to_interface "export_0" "ENET_INT" "export"

# Interface avalon_slave_0
add_interface "avalon_slave_0" "avalon" "slave" "clock"
set_interface_property "avalon_slave_0" "isNonVolatileStorage" "false"
set_interface_property "avalon_slave_0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "avalon_slave_0" "readLatency" "0"
set_interface_property "avalon_slave_0" "holdTime" "0"
set_interface_property "avalon_slave_0" "printableDevice" "false"
set_interface_property "avalon_slave_0" "readWaitTime" "1"
set_interface_property "avalon_slave_0" "setupTime" "0"
set_interface_property "avalon_slave_0" "addressAlignment" "NATIVE"
set_interface_property "avalon_slave_0" "writeWaitTime" "0"
set_interface_property "avalon_slave_0" "timingUnits" "Cycles"
set_interface_property "avalon_slave_0" "minimumUninterruptedRunLength" "1"
set_interface_property "avalon_slave_0" "isMemoryDevice" "false"
set_interface_property "avalon_slave_0" "linewrapBursts" "false"
set_interface_property "avalon_slave_0" "maximumPendingReadTransactions" "0"
# Ports in interface avalon_slave_0
add_port_to_interface "avalon_slave_0" "iCMD" "address"
add_port_to_interface "avalon_slave_0" "iRD_N" "read_n"
add_port_to_interface "avalon_slave_0" "iWR_N" "write_n"
add_port_to_interface "avalon_slave_0" "iDATA" "writedata"
add_port_to_interface "avalon_slave_0" "oDATA" "readdata"
add_port_to_interface "avalon_slave_0" "iCS_N" "chipselect_n"

# Interface interrupt_sender
add_interface "interrupt_sender" "interrupt" "sender" "clock"
set_interface_property "interrupt_sender" "associatedAddressablePoint" "avalon_slave_0"
# Ports in interface interrupt_sender
add_port_to_interface "interrupt_sender" "oINT" "irq"
