# TCL File Generated by Component Editor 10.1sp1
# Wed Apr 10 15:59:06 MDT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sram_IF "sram_IF" v1.0
# | null 2013.04.10.15:59:06
# | 
# | 
# | /afs/ualberta.ca/home/t/h/thohn/ECE492/webServerFlashFinal/sram_IF.vhd
# | 
# |    ./sram_IF.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module sram_IF
# | 
set_module_property NAME sram_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME sram_IF
set_module_property TOP_LEVEL_HDL_FILE sram_IF.vhd
set_module_property TOP_LEVEL_HDL_MODULE sram_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sram_IF.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tsb
# | 
add_interface tsb avalon_tristate end
set_interface_property tsb activeCSThroughReadLatency false
set_interface_property tsb explicitAddressSpan 0
set_interface_property tsb holdTime 0
set_interface_property tsb isMemoryDevice false
set_interface_property tsb isNonVolatileStorage false
set_interface_property tsb maximumPendingReadTransactions 0
set_interface_property tsb printableDevice false
set_interface_property tsb readLatency 0
set_interface_property tsb readWaitTime 1
set_interface_property tsb setupTime 0
set_interface_property tsb timingUnits Cycles
set_interface_property tsb writeWaitTime 0

set_interface_property tsb ENABLED true

add_interface_port tsb ats_tsb_address address Input 18
add_interface_port tsb ats_tsb_data data Bidir 16
add_interface_port tsb ats_tsb_write_n write_n Input 1
add_interface_port tsb ats_tsb_byteenable_n byteenable_n Input 2
add_interface_port tsb ats_tsb_chipselect_n chipselect_n Input 1
add_interface_port tsb ats_tsb_outputenable_n outputenable_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_0
# | 
add_interface conduit_end_0 conduit end

set_interface_property conduit_end_0 ENABLED true

add_interface_port conduit_end_0 coe_sram_address export Output 18
add_interface_port conduit_end_0 coe_sram_writeenable_n export Output 1
add_interface_port conduit_end_0 coe_sram_upperbyte_n export Output 1
add_interface_port conduit_end_0 coe_sram_lowerbyte_n export Output 1
add_interface_port conduit_end_0 coe_sram_chipenable_n export Output 1
add_interface_port conduit_end_0 coe_sram_outputenable_n export Output 1
# | 
# +-----------------------------------
